repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.56.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terrascan
        pass_filenames: false
        args: [-l=examples/complete] #NOTE: this command should point to the directory containing your .tf files
        verbose: true
      # - id: infracost_breakdown
      #   args:
      #     - --args=--path=./examples/complete
      #   verbose: true # Always show costs

      

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
